In [2]:
import gym
import numpy as np

In [3]:
env = gym.make('CartPole-v1')

In [16]:
inc = np.array([.01, 0, 0, 0])
dec = np.array([0.11, 0.1, 0.01, 0.1])
for i in range(1) :
    initial = env.reset()
    while(True) :
        env.render()
        state, reward, done, info = env.step(env.action_space.sample())
        env.unwrapped.state = initial
        if initial[0] < 1 :
            initial -= inc
        
        if initial[0] >=1.2 :
            initial-=dec
        if done :
            break
env.close()

In [17]:
np.amax(env.unwrapped.state, axis=0)

0.02063765583058648

In [18]:
env.unwrapped.state

array([-2.41461293,  0.02063766, -0.03949259,  0.00317   ])

In [34]:
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

/home/anurag/.local/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


KeyboardInterrupt: 

In [71]:
for i_episode in range(2000):
    observation = env.reset()
    for t in range(10000):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.00591933  0.0362545   0.04104935 -0.02221562]
[ 0.00664442  0.23076446  0.04060504 -0.30166964]
[ 0.01125971  0.42528486  0.03457165 -0.58127514]
[ 0.01976541  0.22969599  0.02294615 -0.2779051 ]
[0.02435933 0.03425433 0.01738804 0.02192579]
[ 0.02504441 -0.16111261  0.01782656  0.32004373]
[ 0.02182216 -0.35648384  0.02422743  0.61829474]
[ 0.01469249 -0.16170854  0.03659333  0.3333397 ]
[ 0.01145831 -0.3573317   0.04326012  0.63733403]
[ 0.00431168 -0.16283887  0.0560068   0.35858224]
[ 0.0010549  -0.35871043  0.06317845  0.66838629]
[-0.00611931 -0.16452126  0.07654617  0.39624579]
[-0.00940973 -0.36064108  0.08447109  0.71204669]
[-0.01662255 -0.16678406  0.09871202  0.44710294]
[-0.01995823 -0.36315373  0.10765408  0.76919777]
[-0.02722131 -0.55957975  0.12303804  1.0937203 ]
[-0.0384129  -0.75608869  0.14491244  1.42233739]
[-0.05353468 -0.56302559  0.17335919  1.17823341]
[-0.06479519 -0.37052582  0.19692386  0.94452455]
Episode finished after 19 timesteps
[ 0.01904005  0.00

[ 0.02480045 -0.0323604   0.04558162  0.03373247]
[ 0.02415324  0.16207926  0.04625627 -0.24422773]
[ 0.02739483  0.35651105  0.04137172 -0.52196896]
[ 0.03452505  0.16083193  0.03093234 -0.21654163]
[ 0.03774169 -0.03471825  0.0266015   0.08573599]
[ 0.03704732 -0.23021121  0.02831622  0.3866916 ]
[ 0.0324431  -0.03550243  0.03605006  0.10306937]
[ 0.03173305 -0.23112198  0.03811144  0.40690446]
[ 0.02711061 -0.42676304  0.04624953  0.711355  ]
[ 0.01857535 -0.62249389  0.06047663  1.01822985]
[ 0.00612547 -0.81836756  0.08084123  1.32927252]
[-0.01024188 -1.0144111   0.10742668  1.64611889]
[-0.0305301  -1.21061339  0.14034906  1.97024849]
[-0.05474237 -1.40691097  0.17975403  2.30292692]
Episode finished after 14 timesteps
[-0.01277164  0.03633365 -0.0038664  -0.04774074]
[-0.01204496  0.23151083 -0.00482121 -0.34164103]
[-0.00741475  0.0364578  -0.01165403 -0.05048233]
[-0.00668559  0.23174491 -0.01266368 -0.34681929]
[-0.00205069  0.42704468 -0.01960006 -0.64346848]
[ 0.0064902   

[ 0.03728501  0.41961922 -0.12411279 -0.74717571]
[ 0.04567739  0.22640823 -0.13905631 -0.49598409]
[ 0.05020556  0.42318895 -0.14897599 -0.82905688]
[ 0.05866934  0.61999918 -0.16555713 -1.16463941]
[ 0.07106932  0.42737313 -0.18884992 -0.92810284]
[ 0.07961678  0.23523334 -0.20741197 -0.70020973]
Episode finished after 20 timesteps
[ 0.00825054 -0.036429   -0.02041052 -0.038737  ]
[ 0.00752196  0.1589796  -0.02118526 -0.33778913]
[ 0.01070155  0.35439652 -0.02794104 -0.63707672]
[ 0.01778948  0.54989675 -0.04068258 -0.9384262 ]
[ 0.02878742  0.74554288 -0.0594511  -1.24360996]
[ 0.04369828  0.9413752  -0.0843233  -1.55430781]
[ 0.06252578  1.13740049 -0.11540946 -1.87206268]
[ 0.08527379  1.33357886 -0.15285071 -2.19822778]
[ 0.11194537  1.14022521 -0.19681527 -1.95634209]
Episode finished after 9 timesteps
[-0.04766244  0.04374412 -0.01575244  0.03922383]
[-0.04678756 -0.15114844 -0.01496796  0.32689538]
[-0.04981053 -0.34605413 -0.00843005  0.61482074]
[-0.05673161 -0.15081541  0.0

[-0.0136836   0.81605424 -0.06849505 -1.23682946]
[ 0.00263748  1.01198614 -0.09323164 -1.55015997]
[ 0.0228772   1.20809481 -0.12423484 -1.87041586]
[ 0.0470391   1.01453083 -0.16164316 -1.61873881]
[ 0.06732972  0.82164106 -0.19401794 -1.38049228]
Episode finished after 9 timesteps
[ 0.00575164 -0.0406066   0.0475115  -0.00628515]
[ 0.00493951  0.15380291  0.0473858  -0.28360721]
[ 0.00801557 -0.04196175  0.04171366  0.02363638]
[ 0.00717633  0.15253793  0.04218638 -0.2555991 ]
[ 0.01022709 -0.04316016  0.0370744   0.05008598]
[ 0.00936389 -0.23879357  0.03807612  0.35423182]
[ 0.00458802 -0.04423312  0.04516076  0.07379436]
[ 0.00370336 -0.23997244  0.04663664  0.38037672]
[-0.00109609 -0.43572454  0.05424418  0.68739183]
[-0.00981058 -0.24139581  0.06799202  0.41226744]
[-0.0146385  -0.04730025  0.07623736  0.14177106]
[-0.0155845  -0.24342659  0.07907279  0.45749812]
[-0.02045304 -0.04950634  0.08822275  0.19074982]
[-0.02144316 -0.24577237  0.09203774  0.50990777]
[-0.02635861 -0

[ 0.00194464 -0.20863538 -0.0390576   0.17759042]
[-0.00222807 -0.40317725 -0.03550579  0.45770066]
[-0.01029162 -0.59777974 -0.02635178  0.73898391]
[-0.02224721 -0.40230401 -0.0115721   0.43812558]
[-0.03029329 -0.20702019 -0.00280959  0.14181735]
[-3.44336957e-02 -4.02101790e-01  2.67561473e-05  4.33612574e-01]
[-0.04247573 -0.20698022  0.00869901  0.14093808]
[-0.04661534 -0.01198393  0.01151777 -0.14898781]
[-0.04685501  0.18297121  0.00853801 -0.43801498]
[-4.31955902e-02  3.77971281e-01 -2.22286441e-04 -7.27994271e-01]
[-0.03563616  0.5730963  -0.01478217 -1.02074715]
[-0.02417424  0.37817441 -0.03519711 -0.73274205]
[-0.01661075  0.57376457 -0.04985196 -1.0362914 ]
[-0.00513546  0.3793395  -0.07057778 -0.75966652]
[ 0.00245133  0.57535925 -0.08577111 -1.07369678]
[ 0.01395852  0.77150359 -0.10724505 -1.39201752]
[ 0.02938859  0.96778492 -0.1350854  -1.71621763]
[ 0.04874429  1.16417308 -0.16940975 -2.04771061]
Episode finished after 37 timesteps
[-0.03971392 -0.02773599 -0.0413

KeyboardInterrupt: 