In [2]:
import numpy as np
import random

In [9]:
class TicTac :
    
    def __init__(self) :
        self.state_size = 10
        self.action_size = 9
        
        self.state = np.zeros([10], dtype=int)
        self.state[9] = random.choice([-1, 1])
        self.done = False
    
    def step(self, action) :
        player = self.state[9]
        
        if self.done :
            return np.copy(self.state), -10, True, {}
        
        if self.state[action] != 0 :
            return np.copy(self.state), -10, False, {}
        
        self.state[action] = player
        
        done, reward = self.gen_reward()
        
        self.done = done
        
        self.state[9] = -player
        
        return np.copy(self.state), reward, done, {}
        
    def gen_reward(self) :
        player = self.state[9]
        board = self.state[:-1].reshape(3, 3)
        
        rows = np.any(np.sum(board, axis=1) == player * 3)
        cols = np.any(np.sum(board, axis=0) == player * 3)
        
        d1 = np.sum(board.flatten()[[0,4,8]] == player * 3)
        d2 = np.sum(board.flatten()[[2,4,6]] == player * 3)
        
        
        if np.any([rows, cols, d1, d2]) :
            return True, 10
        elif not np.any(self.state == 0) :
            return True, 1
        else :
            return False, 1

In [38]:
env = TicTac()

In [49]:
state, reward, done, info = env.step()
board = state[:-1].reshape(3,3)
print(board, state[-1], reward, done)

[[-1  1 -1]
 [ 1 -1  1]
 [-1  1 -1]] 1 1 True


In [36]:
858 + 571.2

1429.2

In [37]:
1024*1.4


1433.6